### PR TITLE
Closes #1: Added revenue plot

### LINKED ISSUE #1: Generate a line plot of revenues of Canon, Nikon and Sony
Add a plot of revenue data of Canon, Nikon and Sony using D3.js.

### PR DESCRIPTION
**Pull request by dongskyler**
about: Added a revenue plot of 3 camera brands
reference: This Pull request closes #1

### CODE REVIEW

**Comment by dongskyler** [comment]
@tangaw I changed the 1st column's name from 'year' to 'date' in the revenue CSV file. 

The benefit is: one fewer thing to change in our D3.js template.

And, essentially, year is a kind of date. It just has "%Y" attribute, instead of "%Y-%m-%d".

How about making all future 'date'-kind of things' column names 'date'?

**Review by tangaw — DISMISSED** [review]
Phenomenal work

**Comment by dongskyler** [comment]
@tangaw  I think the 2 issues that Codacy points out are fine. I think the PR can be rebased and merged into the master branch.

**Review by tangaw — APPROVED** [review]
Looks fine to me

**Pull request merged**
